export const openaiSettings = {
  model: 'gpt-3.5-turbo',
  temperature: 0.5,
  max_tokens: 4000,
}

export const imagesCard = [
  require('../images/imgCard1.png'),
  require('../images/imgCard2.png'),
  require('../images/imgCard3.png'),
  require('../images/imgCard4.png'),
  require('../images/imgCard5.png'),
  require('../images/imgCard6.png'),
  require('../images/imgCard7.png'),
  require('../images/imgCard8.png'),
  require('../images/imgCard9.png'),
  require('../images/imgCard10.png'),
  require('../images/imgCard11.png'),
  require('../images/imgCard12.png'),
  require('../images/imgCard13.png'),
  require('../images/imgCard14.png'),
  require('../images/imgCard15.png'),
  require('../images/imgCard16.png'),
  require('../images/imgCard17.png'),
  require('../images/imgCard18.png'),
  require('../images/imgCard19.png'),
  require('../images/imgCard20.png'),
  require('../images/imgCard21.png'),
  require('../images/imgCard22.png'),
  require('../images/imgCard23.png'),
  require('../images/imgCard24.png'),
  require('../images/imgCard25.png'),
  require('../images/imgCard26.png'),
]